/* Extracted from Twitter */

export const lookupList = {
  'International Date Line West': '(GMT-11:00) International Date Line West',
  'Midway Island': '(GMT-11:00) Midway Island',
  Samoa: '(GMT-11:00) Samoa',
  Hawaii: '(GMT-10:00) Hawaii',
  Alaska: '(GMT-09:00) Alaska',
  'Pacific Time (US &amp; Canada)':
    '(GMT-08:00) Pacific Time (US &amp; Canada)',
  Tijuana: '(GMT-08:00) Tijuana',
  'Mountain Time (US &amp; Canada)':
    '(GMT-07:00) Mountain Time (US &amp; Canada)',
  Arizona: '(GMT-07:00) Arizona',
  Chihuahua: '(GMT-07:00) Chihuahua',
  Mazatlan: '(GMT-07:00) Mazatlan',
  'Central Time (US &amp; Canada)':
    '(GMT-06:00) Central Time (US &amp; Canada)',
  Saskatchewan: '(GMT-06:00) Saskatchewan',
  Guadalajara: '(GMT-06:00) Guadalajara',
  'Mexico City': '(GMT-06:00) Mexico City',
  Monterrey: '(GMT-06:00) Monterrey',
  'Central America': '(GMT-06:00) Central America',
  'Eastern Time (US &amp; Canada)':
    '(GMT-05:00) Eastern Time (US &amp; Canada)',
  'Indiana (East)': '(GMT-05:00) Indiana (East)',
  Bogota: '(GMT-05:00) Bogota',
  Lima: '(GMT-05:00) Lima',
  Quito: '(GMT-05:00) Quito',
  'Atlantic Time (Canada)': '(GMT-04:00) Atlantic Time (Canada)',
  Caracas: '(GMT-04:00) Caracas',
  'La Paz': '(GMT-04:00) La Paz',
  Georgetown: '(GMT-04:00) Georgetown',
  Newfoundland: '(GMT-03:30) Newfoundland',
  Santiago: '(GMT-03:00) Santiago',
  'Buenos Aires': '(GMT-03:00) Buenos Aires',
  Greenland: '(GMT-03:00) Greenland',
  Brasilia: '(GMT-02:00) Brasilia',
  'Mid-Atlantic': '(GMT-02:00) Mid-Atlantic',
  Azores: '(GMT-01:00) Azores',
  'Cape Verde Is.': '(GMT-01:00) Cape Verde Is.',
  Dublin: '(GMT) Dublin',
  Edinburgh: '(GMT) Edinburgh',
  Lisbon: '(GMT) Lisbon',
  London: '(GMT) London',
  Casablanca: '(GMT) Casablanca',
  Monrovia: '(GMT) Monrovia',
  UTC: '(GMT) UTC',
  Belgrade: '(GMT+01:00) Belgrade',
  Bratislava: '(GMT+01:00) Bratislava',
  Budapest: '(GMT+01:00) Budapest',
  Ljubljana: '(GMT+01:00) Ljubljana',
  Prague: '(GMT+01:00) Prague',
  Sarajevo: '(GMT+01:00) Sarajevo',
  Skopje: '(GMT+01:00) Skopje',
  Warsaw: '(GMT+01:00) Warsaw',
  Zagreb: '(GMT+01:00) Zagreb',
  Brussels: '(GMT+01:00) Brussels',
  Copenhagen: '(GMT+01:00) Copenhagen',
  Madrid: '(GMT+01:00) Madrid',
  Paris: '(GMT+01:00) Paris',
  Amsterdam: '(GMT+01:00) Amsterdam',
  Berlin: '(GMT+01:00) Berlin',
  Bern: '(GMT+01:00) Bern',
  Rome: '(GMT+01:00) Rome',
  Stockholm: '(GMT+01:00) Stockholm',
  Vienna: '(GMT+01:00) Vienna',
  'West Central Africa': '(GMT+01:00) West Central Africa',
  Bucharest: '(GMT+02:00) Bucharest',
  Cairo: '(GMT+02:00) Cairo',
  Helsinki: '(GMT+02:00) Helsinki',
  Kiev: '(GMT+02:00) Kiev',
  Kyiv: '(GMT+02:00) Kyiv',
  Riga: '(GMT+02:00) Riga',
  Sofia: '(GMT+02:00) Sofia',
  Tallinn: '(GMT+02:00) Tallinn',
  Vilnius: '(GMT+02:00) Vilnius',
  Athens: '(GMT+02:00) Athens',
  Jerusalem: '(GMT+02:00) Jerusalem',
  Harare: '(GMT+02:00) Harare',
  Pretoria: '(GMT+02:00) Pretoria',
  Istanbul: '(GMT+03:00) Istanbul',
  Minsk: '(GMT+03:00) Minsk',
  Moscow: '(GMT+03:00) Moscow',
  'St. Petersburg': '(GMT+03:00) St. Petersburg',
  Volgograd: '(GMT+03:00) Volgograd',
  Kuwait: '(GMT+03:00) Kuwait',
  Riyadh: '(GMT+03:00) Riyadh',
  Nairobi: '(GMT+03:00) Nairobi',
  Baghdad: '(GMT+03:00) Baghdad',
  Tehran: '(GMT+03:30) Tehran',
  'Abu Dhabi': '(GMT+04:00) Abu Dhabi',
  Muscat: '(GMT+04:00) Muscat',
  Baku: '(GMT+04:00) Baku',
  Tbilisi: '(GMT+04:00) Tbilisi',
  Yerevan: '(GMT+04:00) Yerevan',
  Kabul: '(GMT+04:30) Kabul',
  Ekaterinburg: '(GMT+05:00) Ekaterinburg',
  Islamabad: '(GMT+05:00) Islamabad',
  Karachi: '(GMT+05:00) Karachi',
  Tashkent: '(GMT+05:00) Tashkent',
  Chennai: '(GMT+05:30) Chennai',
  Kolkata: '(GMT+05:30) Kolkata',
  Mumbai: '(GMT+05:30) Mumbai',
  'New Delhi': '(GMT+05:30) New Delhi',
  'Sri Jayawardenepura': '(GMT+05:30) Sri Jayawardenepura',
  Kathmandu: '(GMT+05:45) Kathmandu',
  Astana: '(GMT+06:00) Astana',
  Dhaka: '(GMT+06:00) Dhaka',
  Almaty: '(GMT+06:00) Almaty',
  Urumqi: '(GMT+06:00) Urumqi',
  Rangoon: '(GMT+06:30) Rangoon',
  Novosibirsk: '(GMT+07:00) Novosibirsk',
  Bangkok: '(GMT+07:00) Bangkok',
  Hanoi: '(GMT+07:00) Hanoi',
  Jakarta: '(GMT+07:00) Jakarta',
  Krasnoyarsk: '(GMT+07:00) Krasnoyarsk',
  Beijing: '(GMT+08:00) Beijing',
  Chongqing: '(GMT+08:00) Chongqing',
  'Hong Kong': '(GMT+08:00) Hong Kong',
  'Kuala Lumpur': '(GMT+08:00) Kuala Lumpur',
  Singapore: '(GMT+08:00) Singapore',
  Taipei: '(GMT+08:00) Taipei',
  Perth: '(GMT+08:00) Perth',
  Irkutsk: '(GMT+08:00) Irkutsk',
  'Ulaan Bataar': '(GMT+08:00) Ulaan Bataar',
  Seoul: '(GMT+09:00) Seoul',
  Osaka: '(GMT+09:00) Osaka',
  Sapporo: '(GMT+09:00) Sapporo',
  Tokyo: '(GMT+09:00) Tokyo',
  Yakutsk: '(GMT+09:00) Yakutsk',
  Darwin: '(GMT+09:30) Darwin',
  Brisbane: '(GMT+10:00) Brisbane',
  Vladivostok: '(GMT+10:00) Vladivostok',
  Guam: '(GMT+10:00) Guam',
  'Port Moresby': '(GMT+10:00) Port Moresby',
  'Solomon Is.': '(GMT+10:00) Solomon Is.',
  Adelaide: '(GMT+10:30) Adelaide',
  Canberra: '(GMT+11:00) Canberra',
  Melbourne: '(GMT+11:00) Melbourne',
  Sydney: '(GMT+11:00) Sydney',
  Hobart: '(GMT+11:00) Hobart',
  Magadan: '(GMT+11:00) Magadan',
  'New Caledonia': '(GMT+11:00) New Caledonia',
  Fiji: '(GMT+12:00) Fiji',
  Kamchatka: '(GMT+12:00) Kamchatka',
  'Marshall Is.': '(GMT+12:00) Marshall Is.',
  Auckland: '(GMT+13:00) Auckland',
  Wellington: '(GMT+13:00) Wellington',
  "Nuku'alofa": "(GMT+13:00) Nuku'alofa",
}

export const timezonesList = {
  '(GMT-11:00) International Date Line West': 'International Date Line West',
  '(GMT-11:00) Midway Island': 'Midway Island',
  '(GMT-11:00) Samoa': 'Samoa',
  '(GMT-10:00) Hawaii': 'Hawaii',
  '(GMT-09:00) Alaska': 'Alaska',
  '(GMT-08:00) Pacific Time (US &amp; Canada)':
    'Pacific Time (US &amp; Canada)',
  '(GMT-08:00) Tijuana': 'Tijuana',
  '(GMT-07:00) Mountain Time (US &amp; Canada)':
    'Mountain Time (US &amp; Canada)',
  '(GMT-07:00) Arizona': 'Arizona',
  '(GMT-07:00) Chihuahua': 'Chihuahua',
  '(GMT-07:00) Mazatlan': 'Mazatlan',
  '(GMT-06:00) Central Time (US &amp; Canada)':
    'Central Time (US &amp; Canada)',
  '(GMT-06:00) Saskatchewan': 'Saskatchewan',
  '(GMT-06:00) Guadalajara': 'Guadalajara',
  '(GMT-06:00) Mexico City': 'Mexico City',
  '(GMT-06:00) Monterrey': 'Monterrey',
  '(GMT-06:00) Central America': 'Central America',
  '(GMT-05:00) Eastern Time (US &amp; Canada)':
    'Eastern Time (US &amp; Canada)',
  '(GMT-05:00) Indiana (East)': 'Indiana (East)',
  '(GMT-05:00) Bogota': 'Bogota',
  '(GMT-05:00) Lima': 'Lima',
  '(GMT-05:00) Quito': 'Quito',
  '(GMT-04:00) Atlantic Time (Canada)': 'Atlantic Time (Canada)',
  '(GMT-04:00) Caracas': 'Caracas',
  '(GMT-04:00) La Paz': 'La Paz',
  '(GMT-04:00) Georgetown': 'Georgetown',
  '(GMT-03:30) Newfoundland': 'Newfoundland',
  '(GMT-03:00) Santiago': 'Santiago',
  '(GMT-03:00) Buenos Aires': 'Buenos Aires',
  '(GMT-03:00) Greenland': 'Greenland',
  '(GMT-02:00) Brasilia': 'Brasilia',
  '(GMT-02:00) Mid-Atlantic': 'Mid-Atlantic',
  '(GMT-01:00) Azores': 'Azores',
  '(GMT-01:00) Cape Verde Is.': 'Cape Verde Is.',
  '(GMT) Dublin': 'Dublin',
  '(GMT) Edinburgh': 'Edinburgh',
  '(GMT) Lisbon': 'Lisbon',
  '(GMT) London': 'London',
  '(GMT) Casablanca': 'Casablanca',
  '(GMT) Monrovia': 'Monrovia',
  '(GMT) UTC': 'UTC',
  '(GMT+01:00) Belgrade': 'Belgrade',
  '(GMT+01:00) Bratislava': 'Bratislava',
  '(GMT+01:00) Budapest': 'Budapest',
  '(GMT+01:00) Ljubljana': 'Ljubljana',
  '(GMT+01:00) Prague': 'Prague',
  '(GMT+01:00) Sarajevo': 'Sarajevo',
  '(GMT+01:00) Skopje': 'Skopje',
  '(GMT+01:00) Warsaw': 'Warsaw',
  '(GMT+01:00) Zagreb': 'Zagreb',
  '(GMT+01:00) Brussels': 'Brussels',
  '(GMT+01:00) Copenhagen': 'Copenhagen',
  '(GMT+01:00) Madrid': 'Madrid',
  '(GMT+01:00) Paris': 'Paris',
  '(GMT+01:00) Amsterdam': 'Amsterdam',
  '(GMT+01:00) Berlin': 'Berlin',
  '(GMT+01:00) Bern': 'Bern',
  '(GMT+01:00) Rome': 'Rome',
  '(GMT+01:00) Stockholm': 'Stockholm',
  '(GMT+01:00) Vienna': 'Vienna',
  '(GMT+01:00) West Central Africa': 'West Central Africa',
  '(GMT+02:00) Bucharest': 'Bucharest',
  '(GMT+02:00) Cairo': 'Cairo',
  '(GMT+02:00) Helsinki': 'Helsinki',
  '(GMT+02:00) Kiev': 'Kiev',
  '(GMT+02:00) Kyiv': 'Kyiv',
  '(GMT+02:00) Riga': 'Riga',
  '(GMT+02:00) Sofia': 'Sofia',
  '(GMT+02:00) Tallinn': 'Tallinn',
  '(GMT+02:00) Vilnius': 'Vilnius',
  '(GMT+02:00) Athens': 'Athens',
  '(GMT+02:00) Jerusalem': 'Jerusalem',
  '(GMT+02:00) Harare': 'Harare',
  '(GMT+02:00) Pretoria': 'Pretoria',
  '(GMT+03:00) Istanbul': 'Istanbul',
  '(GMT+03:00) Minsk': 'Minsk',
  '(GMT+03:00) Moscow': 'Moscow',
  '(GMT+03:00) St. Petersburg': 'St. Petersburg',
  '(GMT+03:00) Volgograd': 'Volgograd',
  '(GMT+03:00) Kuwait': 'Kuwait',
  '(GMT+03:00) Riyadh': 'Riyadh',
  '(GMT+03:00) Nairobi': 'Nairobi',
  '(GMT+03:00) Baghdad': 'Baghdad',
  '(GMT+03:30) Tehran': 'Tehran',
  '(GMT+04:00) Abu Dhabi': 'Abu Dhabi',
  '(GMT+04:00) Muscat': 'Muscat',
  '(GMT+04:00) Baku': 'Baku',
  '(GMT+04:00) Tbilisi': 'Tbilisi',
  '(GMT+04:00) Yerevan': 'Yerevan',
  '(GMT+04:30) Kabul': 'Kabul',
  '(GMT+05:00) Ekaterinburg': 'Ekaterinburg',
  '(GMT+05:00) Islamabad': 'Islamabad',
  '(GMT+05:00) Karachi': 'Karachi',
  '(GMT+05:00) Tashkent': 'Tashkent',
  '(GMT+05:30) Chennai': 'Chennai',
  '(GMT+05:30) Kolkata': 'Kolkata',
  '(GMT+05:30) Mumbai': 'Mumbai',
  '(GMT+05:30) New Delhi': 'New Delhi',
  '(GMT+05:30) Sri Jayawardenepura': 'Sri Jayawardenepura',
  '(GMT+05:45) Kathmandu': 'Kathmandu',
  '(GMT+06:00) Astana': 'Astana',
  '(GMT+06:00) Dhaka': 'Dhaka',
  '(GMT+06:00) Almaty': 'Almaty',
  '(GMT+06:00) Urumqi': 'Urumqi',
  '(GMT+06:30) Rangoon': 'Rangoon',
  '(GMT+07:00) Novosibirsk': 'Novosibirsk',
  '(GMT+07:00) Bangkok': 'Bangkok',
  '(GMT+07:00) Hanoi': 'Hanoi',
  '(GMT+07:00) Jakarta': 'Jakarta',
  '(GMT+07:00) Krasnoyarsk': 'Krasnoyarsk',
  '(GMT+08:00) Beijing': 'Beijing',
  '(GMT+08:00) Chongqing': 'Chongqing',
  '(GMT+08:00) Hong Kong': 'Hong Kong',
  '(GMT+08:00) Kuala Lumpur': 'Kuala Lumpur',
  '(GMT+08:00) Singapore': 'Singapore',
  '(GMT+08:00) Taipei': 'Taipei',
  '(GMT+08:00) Perth': 'Perth',
  '(GMT+08:00) Irkutsk': 'Irkutsk',
  '(GMT+08:00) Ulaan Bataar': 'Ulaan Bataar',
  '(GMT+09:00) Seoul': 'Seoul',
  '(GMT+09:00) Osaka': 'Osaka',
  '(GMT+09:00) Sapporo': 'Sapporo',
  '(GMT+09:00) Tokyo': 'Tokyo',
  '(GMT+09:00) Yakutsk': 'Yakutsk',
  '(GMT+09:30) Darwin': 'Darwin',
  '(GMT+10:00) Brisbane': 'Brisbane',
  '(GMT+10:00) Vladivostok': 'Vladivostok',
  '(GMT+10:00) Guam': 'Guam',
  '(GMT+10:00) Port Moresby': 'Port Moresby',
  '(GMT+10:00) Solomon Is.': 'Solomon Is.',
  '(GMT+10:30) Adelaide': 'Adelaide',
  '(GMT+11:00) Canberra': 'Canberra',
  '(GMT+11:00) Melbourne': 'Melbourne',
  '(GMT+11:00) Sydney': 'Sydney',
  '(GMT+11:00) Hobart': 'Hobart',
  '(GMT+11:00) Magadan': 'Magadan',
  '(GMT+11:00) New Caledonia': 'New Caledonia',
  '(GMT+12:00) Fiji': 'Fiji',
  '(GMT+12:00) Kamchatka': 'Kamchatka',
  '(GMT+12:00) Marshall Is.': 'Marshall Is.',
  '(GMT+13:00) Auckland': 'Auckland',
  '(GMT+13:00) Wellington': 'Wellington',
  "(GMT+13:00) Nuku'alofa": "Nuku'alofa",
}
